version: '2'

services:
  elasticsearch:
    image: library/elasticsearch:latest
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300"
    volumes:
      - /data

  rabbitmq:
    image: raintank/rabbitmq
    hostname: rabbitmq
    ports:
      - "5672"
      - "15672:15672"

  kafka:
    image: raintank/kafka
    hostname: kafka
    environment:
      ADVERTISED_HOST: kafka
      NUM_PARTITIONS: 16
    ports:
      - "2181:2181"
      - "9092:9092"
      - "9999:9999"
    volumes:
      - /tmp/kafka-logs
      - ../logs/zookeeper:/var/log/zookeeper
      - ../logs/supervisor:/var/log/supervisor

  kafkaready:
    image: raintank/kafkaready
    ports:
      - "10101"
    environment:
            ZOOKEEPER : kafka:2181


  kafkaManager:
    image: sheepkiller/kafka-manager
    hostname: kafka-manager
    environment:
            ZK_HOSTS: kafka:2181
            APPLICATION_SECRET: somesalt
    ports:
      - "9000:9000"

  kafkaOffsetMonitor:
    image: jpodeszwik/kafka-offset-monitor:0.2.1
    hostname: kafka-offset-monitor
    environment:
            ZK: kafka
    ports:
      - "8080:8080"

  graphitewatcher:
    image: raintank/graphitewatcher
    hostname: watcher
    ports:
      - "6065:6065"
    links:
      - graphiteMetrictank:graphite-api
    volumes:
      - ../logs:/var/log/raintank
      - ../code/inspect:/go/src/github.com/raintank/inspect

  metrictank0:
    image: raintank/metrictank
    hostname: metrictank0
    ports:
      - "6070:6063"
    volumes:
      - ../logs:/var/log/raintank
      - ./metrictank:/etc/raintank
      - ../code/metrictank/build/metrictank:/usr/bin/metrictank
    environment:
      WAIT_HOSTS: kafka:9092,elasticsearch:9200,toxiproxy:9042,kafkaready:10101
      WAIT_TIMEOUT: 30
      MT_KAFKA_MDM_IN_PARTITIONS : 0,1,2,3
      MT_INSTANCE: metrictank0
      MT_LOG_LEVEL: 1
      MT_CLUSTER_MODE: multi
      MT_CLUSTER_PEERS: metrictank1:6063,metrictank2:6063,metrictank3:6063,metrictank4:6063,metrictank5:6063,metrictank6:6063,metrictank7:6063
      MT_CLUSTER_PRIMARY_NODE: "true"

  metrictank1:
    image: raintank/metrictank
    hostname: metrictank1
    ports:
      - "6071:6063"
    volumes:
      - ../logs:/var/log/raintank
      - ./metrictank:/etc/raintank
      - ../code/metrictank/build/metrictank:/usr/bin/metrictank
    environment:
      WAIT_HOSTS: kafka:9092,elasticsearch:9200,toxiproxy:9042,metrictank0:6063
      WAIT_TIMEOUT: 30
      MT_KAFKA_MDM_IN_PARTITIONS : 0,1,2,3
      MT_INSTANCE: metrictank1
      MT_LOG_LEVEL: 1
      MT_CLUSTER_MODE: multi
      MT_CLUSTER_PEERS: metrictank0:6063,metrictank2:6063,metrictank3:6063,metrictank4:6063,metrictank5:6063,metrictank6:6063,metrictank7:6063

  metrictank2:
    image: raintank/metrictank
    hostname: metrictank2
    ports:
      - "6072:6063"
    volumes:
      - ../logs:/var/log/raintank
      - ./metrictank:/etc/raintank
      - ../code/metrictank/build/metrictank:/usr/bin/metrictank
    environment:
      WAIT_HOSTS: kafka:9092,elasticsearch:9200,toxiproxy:9042,metrictank0:6063
      WAIT_TIMEOUT: 30
      MT_KAFKA_MDM_IN_PARTITIONS : 4,5,6,7
      MT_INSTANCE: metrictank2
      MT_LOG_LEVEL: 1
      MT_CLUSTER_MODE: multi
      MT_CLUSTER_PEERS: metrictank0:6063,metrictank1:6063,metrictank3:6063,metrictank4:6063,metrictank5:6063,metrictank6:6063,metrictank7:6063
      MT_CLUSTER_PRIMARY_NODE: "true"

  metrictank3:
    image: raintank/metrictank
    hostname: metrictank3
    ports:
      - "6073:6063"
    volumes:
      - ../logs:/var/log/raintank
      - ./metrictank:/etc/raintank
      - ../code/metrictank/build/metrictank:/usr/bin/metrictank
    environment:
      WAIT_HOSTS: kafka:9092,elasticsearch:9200,toxiproxy:9042,metrictank0:6063
      WAIT_TIMEOUT: 30
      MT_KAFKA_MDM_IN_PARTITIONS : 4,5,6,7
      MT_INSTANCE: metrictank3
      MT_LOG_LEVEL: 1
      MT_CLUSTER_MODE: multi
      MT_CLUSTER_PEERS: metrictank0:6063,metrictank1:6063,metrictank2:6063,metrictank4:6063,metrictank5:6063,metrictank6:6063,metrictank7:6063

  metrictank4:
    image: raintank/metrictank
    hostname: metrictank4
    ports:
      - "6074:6063"
    volumes:
      - ../logs:/var/log/raintank
      - ./metrictank:/etc/raintank
      - ../code/metrictank/build/metrictank:/usr/bin/metrictank
    environment:
      WAIT_HOSTS: kafka:9092,elasticsearch:9200,toxiproxy:9042,metrictank0:6063
      WAIT_TIMEOUT: 30
      MT_KAFKA_MDM_IN_PARTITIONS : 8,9,10,11
      MT_INSTANCE: metrictank4
      MT_LOG_LEVEL: 1
      MT_CLUSTER_MODE: multi
      MT_CLUSTER_PEERS: metrictank0:6063,metrictank1:6063,metrictank2:6063,metrictank3:6063,metrictank5:6063,metrictank6:6063,metrictank7:6063
      MT_CLUSTER_PRIMARY_NODE: "true"

  metrictank5:
    image: raintank/metrictank
    hostname: metrictank5
    ports:
      - "6075:6063"
    volumes:
      - ../logs:/var/log/raintank
      - ./metrictank:/etc/raintank
      - ../code/metrictank/build/metrictank:/usr/bin/metrictank
    environment:
      WAIT_HOSTS: kafka:9092,elasticsearch:9200,toxiproxy:9042,metrictank0:6063
      WAIT_TIMEOUT: 30
      MT_KAFKA_MDM_IN_PARTITIONS : 8,9,10,11
      MT_INSTANCE: metrictank5
      MT_LOG_LEVEL: 1
      MT_CLUSTER_MODE: multi
      MT_CLUSTER_PEERS: metrictank0:6063,metrictank1:6063,metrictank2:6063,metrictank3:6063,metrictank4:6063,metrictank6:6063,metrictank7:6063

  metrictank6:
    image: raintank/metrictank
    hostname: metrictank6
    ports:
      - "6076:6063"
    volumes:
      - ../logs:/var/log/raintank
      - ./metrictank:/etc/raintank
      - ../code/metrictank/build/metrictank:/usr/bin/metrictank
    environment:
      WAIT_HOSTS: kafka:9092,elasticsearch:9200,toxiproxy:9042,metrictank0:6063
      WAIT_TIMEOUT: 30
      MT_KAFKA_MDM_IN_PARTITIONS : 12,13,14,15
      MT_INSTANCE: metrictank6
      MT_LOG_LEVEL: 1
      MT_CLUSTER_MODE: multi
      MT_CLUSTER_PEERS: metrictank0:6063,metrictank1:6063,metrictank2:6063,metrictank3:6063,metrictank4:6063,metrictank5:6063,metrictank7:6063
      MT_CLUSTER_PRIMARY_NODE: "true"

  metrictank7:
    image: raintank/metrictank
    hostname: metrictank7
    ports:
      - "6077:6063"
    volumes:
      - ../logs:/var/log/raintank
      - ./metrictank:/etc/raintank
      - ../code/metrictank/build/metrictank:/usr/bin/metrictank
    environment:
      WAIT_HOSTS: kafka:9092,elasticsearch:9200,toxiproxy:9042,metrictank0:6063
      WAIT_TIMEOUT: 30
      MT_KAFKA_MDM_IN_PARTITIONS : 12,13,14,15
      MT_INSTANCE: metrictank7
      MT_LOG_LEVEL: 1
      MT_CLUSTER_MODE: multi
      MT_CLUSTER_PEERS: metrictank0:6063,metrictank1:6063,metrictank2:6063,metrictank3:6063,metrictank4:6063,metrictank5:6063,metrictank6:6063

  eventtank:
    image: raintank/eventtank
    hostname: npee
    ports:
      - "6062:6060"
    environment:
            WAIT_HOSTS: kafka:9092,elasticsearch:9200,statsdaemon:8125
    volumes:
      - ../code/eventtank/build:/go/bin/

  graphitemon:
    image:  raintank/graphite
    hostname: graphitemon
    ports:
      - "2003:2003"
      - "8000:80"

  toxiproxy:
    image: shopify/toxiproxy
    hostname: toxiproxy
    links:
      - cassandra:cassandra
    ports:
      - "8474"

  cassandra:
    image: cassandra:3.0.8
    hostname: cassandra
    ports:
      - "9160"
      - "8888"

  mysql:
    image: mysql
    hostname: mysql
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: grafana
      MYSQL_USER: grafana
      MYSQL_PASSWORD: password
    volumes:
      - /var/lib/mysql

  graphiteMetrictank:
    image: raintank/graphite-metrictank
    hostname: graphite
    ports:
      - "8888:8888"
    environment:
      WAIT_HOSTS: elasticsearch:9200,metrictank0:6063
    volumes:
      - ../logs:/var/log/raintank
      - ./graphite-metrictank/graphite-metrictank.yaml:/etc/graphite-metrictank/graphite-metrictank.yaml

  worldpingApi:
    image: raintank/worldping-api
    hostname: worldping-api
    ports:
      - "80:80"
    links:
      - graphiteMetrictank:graphite-api
    depends_on:
      - mysql
    environment:
      WAIT_HOSTS: kafka:9092,mysql:3306,rabbitmq:5672
      WAIT_TIMEOUT: 30
    volumes:
      - ./worldping-api/:/etc/raintank/

  statsdaemon:
    image: raintank/statsdaemon
    hostname: statsdaemon
    ports:
      - "8126:8126"

  benchmark:
    image: raintank/benchmark
    hostname: benchmark
    volumes:
      - ../code/inspect:/go/src/github.com/raintank/inspect
      - ../code/fakemetrics:/go/src/github.com/raintank/fakemetrics
      - ../code/toxiproxy:/go/src/github.com/Shopify/toxiproxy/
      - ./benchmark/scripts:/scripts/
      - ../logs:/var/log/raintank
      - ../results:/opt/raintank/raintank-tsdb-benchmark/results
    ports:
      - "6764:6764"
    links:
      - graphiteMetrictank:graphite-api
      - metrictank0:metrictank
      - toxiproxy:toxiproxy

  grafana:
    image: raintank/grafana
    hostname: grafana
    ports:
      - "3000:3000"
    links:
      - metrictank0:metrictank
      - proxy:tsdb-gw.raintank.io
      - proxy:worldping-api.raintank.io
    volumes:
      - ../code/grafana/bin/:/usr/sbin/
      - ../code/raintank-worldping-app:/var/lib/grafana/plugins/raintank-worldping-app
      - ../logs:/var/log/raintank

  tsdbgw:
    image: raintank/tsdb-gw
    hostname: tsdb-gw.raintank.io
    ports:
      - "8081:80"
    links:
      - graphiteMetrictank:graphite-api
    environment:
      WAIT_HOSTS: kafka:9092
    volumes:
      - ./tsdb-gw/:/etc/raintank/

  carbon-relay-ng:
    image: raintank/carbon-relay-ng
    hostname: carbon-relay-ng
    ports:
      - "8083:8083"
      - "2013:2013"
    depends_on:
            - graphitemon
    volumes:
      - ../code/carbon-relay-ng:/go/src/github.com/graphite-ng/carbon-relay-ng
    
  collectd:
    image: raintank/collectd
    hostname: collectd

  proxy:
    image: raintank/proxy
    hostname: proxy
    ports:
      - "443:443"
    links:
      - tsdbgw:tsdb-gw
      - worldpingApi:worldping-api

